- .github/workflows/ci.yml
> feat: Add cargo publish action

- Cargo.lock
- Cargo.toml
- crates/asm-gen/Cargo.toml
- crates/check/Cargo.toml
- crates/constraint-asm/Cargo.toml
- crates/constraint-vm/Cargo.toml
- crates/hash/Cargo.toml
- crates/sign/Cargo.toml
- crates/state-asm/Cargo.toml
- crates/state-read-vm/Cargo.toml
- crates/types/Cargo.toml
- crates/types/src/lib.rs
> feat: remove batch from block

- crates/state-read-vm/src/state_read.rs
> docs: update `word_range` -> `key_range`

- crates/check/src/solution.rs
Previously, reading the full pre and post state slots for a predicate was unnecessarily inlined alongside the constraint checking.
This refactors out a `predicate_state_slots` fn for the potential use-case where only a subset of a predicate's constraints need checking.
Still may need to do some `check_predicate_constraints` refactor in follow-up to make it easier to check individual constraints.
This PR also removes a couple of unnecessary trait bounds, but this is non-breaking.
> refactor: Expose `predicate_state_slots` fn from `essential-check`

- Cargo.lock
- Cargo.toml
- crates/asm-spec/asm.yml
- crates/check/tests/encoding.rs
- crates/check/tests/solution.rs
- crates/check/tests/util.rs
- crates/constraint-vm/Cargo.toml
- crates/constraint-vm/src/access.rs
- crates/constraint-vm/src/access/dec_vars.rs
- crates/constraint-vm/src/access/pub_vars.rs
- crates/constraint-vm/src/access/state.rs
- crates/constraint-vm/src/access/test_utils.rs
- crates/constraint-vm/src/access/tests.rs
- crates/constraint-vm/src/error.rs
- crates/constraint-vm/src/lib.rs
- crates/constraint-vm/src/pred.rs
- crates/constraint-vm/src/pred/tests.rs
- crates/constraint-vm/src/sets.rs
- crates/constraint-vm/src/sets/tests.rs
- crates/constraint-vm/src/stack.rs
- crates/constraint-vm/tests/repeats.rs
- crates/state-read-vm/tests/vm.rs
closes #163 
This makes the changes set out in the above issue and also adds a lot of thorough tests.
> Refactoring and testing access ops

- crates/check/benches/check_contract.rs
- crates/check/src/lib.rs
- crates/check/src/predicate.rs
- crates/check/src/solution.rs
- crates/check/tests/encoding.rs
- crates/check/tests/predicate.rs
- crates/check/tests/solution.rs
- crates/check/tests/util.rs
- crates/hash/tests/hash.rs
- crates/sign/tests/sign.rs
- crates/types/src/predicate.rs
remove directive as it's unused and there are other ways to achieve this without changes to the types
> feat: remove unused directive

- crates/asm-spec/asm.yml
- crates/constraint-vm/src/access.rs
- crates/constraint-vm/src/access/num_slots.rs
- crates/constraint-vm/src/error.rs
- crates/constraint-vm/src/lib.rs
Adds the `NumSlots` op that lets you check either the total number of dec vars, pre state slots, post state slots.
> feat: NumSlots op

- crates/asm-spec/asm.yml
- crates/constraint-vm/src/alu.rs
- crates/constraint-vm/src/alu/shifts.rs
- crates/constraint-vm/src/lib.rs
- crates/types/src/lib.rs
Adds some basic bitwise and shifting operations.
> feat: bitand, bitor, shl, shr, arithmetic_shr

- crates/hash/src/address_impl.rs
- crates/types/src/predicate.rs
- crates/types/src/predicate/encode_predicate.rs
- crates/types/src/predicate/encode_predicate/tests.rs
- predicate encoding, decoding
- program encoding, decoding
- programs encoding, decoding
- hash predicate using encoding
> feat: encode / decode predicate

- Cargo.lock
- Cargo.toml
- crates/asm-gen/Cargo.toml
- crates/asm-spec/Cargo.toml
- crates/asm-spec/asm.yml
- crates/check/Cargo.toml
- crates/constraint-asm/Cargo.toml
- crates/constraint-vm/Cargo.toml
- crates/constraint-vm/src/crypto.rs
- crates/constraint-vm/src/crypto/tests.rs
- crates/hash/Cargo.toml
- crates/sign/Cargo.toml
- crates/sign/src/encode.rs
- crates/sign/src/lib.rs
- crates/state-asm/Cargo.toml
- crates/state-read-vm/Cargo.toml
- crates/types/Cargo.toml
changes include:
- removal of pub vars / transient data
- removal of pathways
- removal of predicate at
- addition of predicate exists
> publish: publish new versions of crates

- crates/asm-spec/asm.yml
- crates/constraint-vm/src/lib.rs
- crates/constraint-vm/src/memory.rs
- crates/constraint-vm/src/memory/tests.rs
- crates/constraint-vm/src/stack.rs
- crates/constraint-vm/src/stack/frame_tests.rs
- adds store range to memory
- adds load range to memory
- adds free to memory
- adds reserve to stack
- adds store to stack
- adds load to stack
Mostly tests
> feat: memory and stack operations

- crates/types/src/fmt.rs
- crates/types/src/lib.rs
> feat: impl core::fmt::Debug for ContentAddress

- crates/types/src/convert.rs
> feat: conversions between `Vec<Word>` and hex str

- crates/asm-spec/asm.yml
- crates/check/tests/solution.rs
- crates/vm/src/memory/tests.rs
- crates/vm/src/stack.rs
- crates/vm/src/stack/frame_tests.rs
- crates/vm/src/sync.rs
- crates/vm/tests/repeats.rs
Changes the index position for all store ops
closes #247
> Change store index position

- Cargo.lock
- Cargo.toml
- crates/asm-gen/Cargo.toml
- crates/asm-spec/Cargo.toml
- crates/asm/Cargo.toml
- crates/check/Cargo.toml
- crates/vm/Cargo.toml
> bump and publish

- crates/check/Cargo.toml
- crates/check/tests/throughput.rs
- crates/vm/src/lib.rs
- crates/vm/tests/sync_vs_async.rs
Adds some throughput tests that compare async to sync
closes #295
> test throughput on check, vm sync vs async

- crates/types/src/fmt.rs
- crates/types/src/solution/decode.rs
- crates/types/src/solution/decode/tests.rs
- crates/types/src/solution/encode.rs
> Fix decoding of mutations

- Cargo.lock
- Cargo.toml
- crates/check/Cargo.toml
- crates/check/src/solution.rs
- crates/check/tests/throughput.rs
- crates/vm/src/error.rs
- crates/vm/src/lib.rs
- crates/vm/src/state_read.rs
- crates/vm/src/state_read/tests.rs
- crates/vm/src/sync.rs
- crates/vm/src/vm.rs
- crates/vm/tests/util.rs
- crates/vm/tests/vm.rs
This creates a sync version of the VM and Essential check. Work is again divided into commits for ease of review.
I'm not sure if we should merge this on not. We probably should but would love some feedback first
closes #290 
closes #291 
closes #292 
closes #293 
closes #298 
closes #299 
closes #300 
closes #297
> Sync VM and Check

- crates/asm-spec/asm.yml
- crates/check/src/solution.rs
- crates/check/src/solution/tests.rs
- crates/check/tests/encoding.rs
- crates/check/tests/solution.rs
- crates/check/tests/throughput.rs
- crates/check/tests/util.rs
- crates/vm/src/lib.rs
- crates/vm/src/state_read.rs
- crates/vm/src/sync.rs
- crates/vm/src/vm.rs
- crates/vm/tests/util.rs
- PostKeyRange
- PostKeyRangeExtern
closes #227
> Adds pre and post state read ops

- crates/asm-spec/asm.yml
- crates/check/src/solution.rs
- crates/vm/src/access.rs
- crates/vm/src/access/dec_vars.rs
- crates/vm/src/access/predicate_exists.rs
- crates/vm/src/access/tests.rs
- crates/vm/src/alu.rs
- crates/vm/src/cached.rs
- crates/vm/src/crypto/tests.rs
- crates/vm/src/lib.rs
- crates/vm/src/memory/tests.rs
- crates/vm/src/pred.rs
- crates/vm/src/sets.rs
- crates/vm/src/sets/tests.rs
- crates/vm/src/stack.rs
- crates/vm/src/sync.rs
- crates/vm/src/total_control_flow/tests.rs
- crates/vm/src/vm.rs
- crates/vm/tests/repeats.rs
- crates/vm/tests/state_read.rs
- crates/vm/tests/throughput.rs
- crates/vm/tests/util.rs
- crates/vm/tests/vm.rs
- Removes mut keys from access and spec
- Makes Access solutions `Arc<Vec<Solution>>`
Closes #272
> Access changes

- .github/workflows/ci.yml
- Cargo.lock
- crates/check/Cargo.toml
- crates/check/benches/check_contract.rs
- crates/vm/benches/eval.rs
> update benches and add to CI

- crates/check/src/solution.rs
- crates/check/src/solution/test_state_read_fallback.rs
- crates/vm/src/access/dec_vars.rs
> Fix fallback bug

- crates/check/tests/throughput.rs
> Add two pass to throughput tests
