crates/constraint-vm/src/pred.rs
crates/constraint-vm/src/pred/tests.rs
crates/constraint-vm/src/stack.rs

I noticed a chance to simplify the `eq_set` implementation a little by refactoring out some parts into another potentially useful `Stack` method, so I thought I'd open a little refactor PR against #155. Feel free to take or leave it!

refactor: Small tweaks to #155, refactor out `Stack::pop_len_words2`

---

crates/asm-spec/asm.yml
crates/constraint-vm/src/access.rs
crates/constraint-vm/src/access/tests.rs
crates/constraint-vm/src/error.rs
crates/constraint-vm/src/lib.rs
crates/constraint-vm/src/pred.rs
crates/constraint-vm/src/pred/tests.rs
crates/constraint-vm/src/stack.rs

Also removes `MutKeysContains` and `MutKeysLen`.
Pushes the mutable keys onto the stack.
The order is unknown as this is a set.
The encoding is:
```
[key_0, key_0_len, ...key_N, key_N_len, total_length]
```
Note that `key_0` might not be the first key in the mutations.
Compares two sets for equality.
Sets are encoded as:
```
[key_0, key_0_len, ...key_N, key_N_len, total_length]
```
So the input would look like:
```
[
set_A_key_0, set_A_key_0_len, ...set_A_key_N, set_A_key_N_len, set_A_total_length,
set_B_key_0, set_B_key_0_len, ...set_B_key_N, set_B_key_N_len, set_B_total_length
]
```
Note there is a length for both sets (which differs to `EqRange`). This is required to prevent the ordering of equality mattering. If we only use a single length then something like:
```
[mut_key_0, …
```

feat: Add MutKeys and EqSet

---

crates/asm-spec/asm.yml
crates/state-read-vm/src/future.rs
crates/state-read-vm/tests/vm.rs

Removes the requirement for a state read program to include halt at the end. This is possible because the program can only move forward or loop a fixed amount of times.

feat: remove requirement for halt

---

Cargo.toml
crates/check/benches/check_contract.rs
crates/check/src/predicate.rs
crates/check/src/solution.rs
crates/check/tests/encoding.rs
crates/check/tests/solution.rs
crates/check/tests/util.rs
crates/hash/src/address_impl.rs
crates/hash/src/block_addr.rs
crates/hash/src/contract_addr.rs
crates/hash/src/lib.rs
crates/hash/tests/hash.rs
crates/sign/src/contract.rs

closes https://github.com/essential-contributions/essential-node/issues/39
Adds the `Address` trait so that the `essential_hash::content_addr()` function will always produce the correct hash.

feat: add Address trait to standardize content_addr()

---

crates/check/src/predicate.rs
crates/check/tests/predicate.rs
crates/hash/src/address_impl.rs
crates/hash/tests/hash.rs
crates/sign/tests/sign.rs
crates/types/src/contract.rs
crates/types/src/lib.rs
crates/types/src/predicate.rs
crates/types/src/predicate/header.rs
crates/types/src/predicate/header/error.rs
crates/types/src/predicate/header/tests.rs
crates/types/src/predicate/tests.rs

This introduces a encoding and decoding scheme for predicates.
The best place to start would be the `types/src/predicate/header.rs` as it contains the main logic around how the encoding header is created and the bytes layout.
There are some more high level functions on the `Predicate` itself.
I would suggest generating the docs `cargo doc -p essential-types --open`.
Additionally:
- The hashing has been updated to use this encoding.
- The limits on sizes have been moved to the `Predicate` so that when encoding / decoding the sizes can be checked.
- The encoding is also documented thoroughly in the `header.rs` module.
- There is thorough test coverage

feat: encode predicate and hash

---

crates/hash/src/contract_addr.rs
crates/hash/src/lib.rs
crates/sign/tests/sign.rs

Somehow this wasn't included in the predicate encode PR 🤷‍♀️

feat: Hash encoded predicates

---

crates/asm-spec/asm.yml
crates/constraint-vm/src/error.rs
crates/constraint-vm/src/lib.rs
crates/constraint-vm/src/total_control_flow.rs
crates/constraint-vm/src/total_control_flow/tests.rs

Adds a panic op that returns the stack at the time of panic in the error. Useful for debugging but also failing on a state read if something is incorrect (like nil when shouldn't be).

feat: PanicIf op

---

crates/asm-spec/asm.yml
crates/check/tests/encoding.rs
crates/constraint-vm/src/crypto.rs
crates/constraint-vm/src/crypto/tests.rs
crates/constraint-vm/src/error.rs
crates/types/src/convert.rs

Adds an arg to `Sha256` that lets you specify the amount of padding to chop off the last word so that you can hash at byte granularity.

feat: sha256 byte granularity

---

crates/asm-gen/src/lib.rs
crates/asm-spec/asm.yml
crates/asm-spec/src/lib.rs
crates/check/tests/util.rs
crates/constraint-asm/src/lib.rs
crates/state-asm/src/lib.rs

Generates shorthand consts to make writing ASM easier.
For constraints do:
```rust
use essential_constraint_asm::short::*;
```
For state reads do:
```rust
use essential_constraint_asm::short::*;
```
I would recommend generating the docs:
```bash
cargo doc --open -p essential-state-asm
```
```bash
cargo doc --open -p essential-constraint-asm
```
and checking out the `short` module.
I also updated the `test_predicate_42` in `check::tests::utils` as an example.

feat: shorthand consts for every op

---

crates/asm-spec/asm.yml
crates/constraint-vm/src/access.rs
crates/constraint-vm/src/access/predicate_exists.rs
crates/constraint-vm/src/cached.rs
crates/constraint-vm/src/lib.rs
crates/state-read-vm/src/lib.rs

Note that the dec vars have to be encoded with lengths before hashing them to distinguish between `[[0], [1, 2]]` and `[[0, 1], [2]]`.
I also added a `LazyCache` for the hashing so that if this op is not used the cost isn't paid but if it is it's only computed once.

feat: add predicate exists op

---

crates/types/src/predicate.rs
crates/types/src/predicate/encode.rs
crates/types/src/predicate/encode/tests.rs

Under the new program DAG model proposed in #212, `Program`s will now be deployed independently from `Predicate`s.
After doing up a brief design for `Program` deployment (see [this issue](https://github.com/essential-contributions/essential-node/issues/148) downstream), it seems that we shouldn't need any special encoding for `Program`, nor any awareness of `Programs` sets at all.
A `Program`'s encoding is now its bytecode slice.
Muiltiple `Program`s can be deployed at once under multiple unique `Mutation`s within a single `Solution`.

refactor: Remove custom `Program` and `Programs` encoding

---

Cargo.lock
Cargo.toml
crates/asm-gen/Cargo.toml
crates/asm-spec/Cargo.toml
crates/check/Cargo.toml
crates/constraint-asm/Cargo.toml
crates/constraint-vm/Cargo.toml
crates/hash/Cargo.toml
crates/sign/Cargo.toml
crates/state-asm/Cargo.toml
crates/state-read-vm/Cargo.toml
crates/types/Cargo.toml

Bumping versions for a new release prior to updating `essential-node` to the latest base versions (required to land essential-contributions/essential-node#146) and prior to publishing new versions of the node and builder with breaking changes to the DB.
Includes:
- New `Debug` implementation for `ContentAddress` (#218)
- The new memory and stack ops (#213)

feat: Publish new versions of all essential-base crates

---

crates/hash/src/address_impl.rs
crates/hash/src/lib.rs
crates/hash/src/solution_addr.rs
crates/hash/tests/hash.rs

Currently, `Solution`'s implementation of `Address` means that different orderings of the same set of `SolutionData` will result in different `ContentAddress`es.
Two `Solution`s with the same `SolutionData`s in different orderings should be semantically equivalent, as `Solution`s are sets of `SolutionData`.
This changes the `Solution`'s `Address` implementation to hash over the inner `SolutionData` in order of their address, similar to how a `Contract`'s address is produced by hashing its `Predicate`s ordered by their `ContentAddress`es. As a result, two `Solution`s with the same `SolutionData` stored in different orders will now produce the same `ContentAddress`.
As a part of this work, a `SolutionData` `Address` implementation has been added.
`SolutionData` has a similar issue, where …

feat: Improve `Solution` `Address` implementation

---

crates/asm-spec/asm.yml

This aims to space out some of the `Access` opcodes to provide space for potential future additions and consolidate the existing control flow opcodes.
Closes #233.

refactor: Review opcodes. Add spacing for potential future access ops. Consolidate control flow ops.

---

.github/workflows/ci.yml
crates/check/src/predicate.rs
crates/hash/src/contract_addr.rs
crates/hash/src/solution_addr.rs
crates/sign/src/contract.rs
crates/sign/src/lib.rs
crates/vm/src/cached.rs
crates/vm/src/lib.rs

Also addresses some doc issues currently present in `cargo doc` warnings.
This PR is against #212 as #212 is pretty close to landing and this avoids the need for another rebase onto `main`.
Closes #231

ci: Add a cargo doc job for checking lints, deny warnings

---

crates/asm-spec/asm.yml
crates/vm/src/memory.rs
crates/vm/src/memory/tests.rs

This is useful for cases where we're freeing down to some dynamically known length which may or may not be empty.
Freeing down to a length that is equal to the current length is a no-op.
Addresses [this comment](https://github.com/essential-contributions/essential-base/pull/212#discussion_r1861205717).

feat: Change `Memory::Free` to allow specifying a new `len` equal to current `memory.len()`

---

Cargo.lock
Cargo.toml
crates/asm-gen/Cargo.toml
crates/asm-spec/Cargo.toml
crates/asm/Cargo.toml
crates/check/Cargo.toml
crates/hash/Cargo.toml
crates/sign/Cargo.toml
crates/types/Cargo.toml
crates/vm/Cargo.toml

This prepares the `develop` branch to auto-publish all of the changes under new crate versions when we merge it into `main`.

feat: Bump all crate versions, ready for publishing DAG changes

---

Cargo.lock
Cargo.toml
crates/asm-gen/Cargo.toml
crates/asm/Cargo.toml
crates/check/Cargo.toml
crates/sign/Cargo.toml
crates/vm/Cargo.toml

Bumping the rest of the crates that depend on `essential-types` or `essential-hash`

versions: bump

---

crates/vm/src/vm.rs

Fixes an issue where Clippy was complaining that lifetimes can be ellided.

Fix issue with clippy in CI

---

crates/asm-spec/asm.yml
crates/vm/src/stack.rs
crates/vm/src/stack/frame_tests.rs

Simple PR that just returns the position of the start of the newly reserved space.
Can also be used to get the length of the stack by reserving zero

Reserve returns the index where the reserved space starts

---

crates/asm-spec/asm.yml
crates/vm/src/sync.rs

Adds an op to drop n from the top of the stack. Useful for clearing reserved space

Add drop from stack op

---

crates/check/src/solution.rs
crates/check/src/solution/tests.rs
crates/check/tests/solution.rs
crates/types/src/fmt.rs
crates/types/src/solution.rs
crates/types/src/solution/decode.rs
crates/types/src/solution/decode/tests.rs
crates/types/src/solution/encode.rs
crates/types/src/solution/encode/tests.rs

The commits in this PR are very self contained. I strongly suggest reviewing each commit in order.
- Layout of a mutation is key_len, key..., value_len, value...
- Layout of a list of mutations is num_mutations, mutation 1, mutation 2, ...
closes #278
The output can be:
- Satisfied true. Indicated by stask[..] == [1]
- Satisfied false. Indicated by stack[..] != [1] && stack[..] != [2]
- DataOutput Memory. Indicated by stack[..] == [2]
closes #277 
- Checks can now return data as part of their output.
- Each solution has a (possibly empty) vector of data outputs.
- Currently the only output is memory.
closes #279 
closes #280 
- This function takes a solution set without mutations
and computes the mutations.
- It returns the modified `SolutionSet` with mutations.
- Mutations are encoded …

Compute Mutations

---

crates/vm/src/bytecode.rs
crates/vm/src/lib.rs
crates/vm/src/op_access.rs
crates/vm/src/repeat.rs
crates/vm/src/sync.rs
crates/vm/src/vm.rs
crates/vm/tests/vm.rs

Some changes to the VM in preparation for Compute and ComputeEnd ops (#262):
- `struct Vm` is `Clone`
- `trait OpAccess` takes `&self` instead of `&mut self`
- This makes `struct BytecodeMappedLazy` and the related `exec_bytecode_iter` obsolete
Closes #271
Closes #274

VM changes

---

crates/asm/src/effects.rs
crates/check/benches/check_contract.rs
crates/check/src/solution.rs
crates/check/src/solution/test_graph_ops.rs
crates/check/src/solution/tests.rs
crates/check/tests/encoding.rs
crates/check/tests/solution.rs
crates/check/tests/throughput.rs
crates/vm/benches/eval.rs

- Adds function to check a function for any post state reads
- Adds in check_predicate_inner (see docs for info)
- Cache is global and can be used across runs
- There are two run modes, outputs or checks
Add two pass run
- First pass generates outputs and ignores post state reads
- Second pass checks outputs by only running the post state reads and
their children.
- Any parents from the first pass are cached.
closes #306 
closes #307 
closes #308 
closes #310 
closes #311

check program for post state
